---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Terminate every running instance in the specified region
      amazon.aws.ec2_instance:
        region: us-east-1           # Specify your region 
        aws_access_key: "{{ec2_access_key}}"  # From vault as defined
        aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined   
        state: absent
        filters:
          instance-state-name: running   # Filter for running instances
          #instance-id: i-0abcd1234efgasa   by id
      register: terminated_instances
    - name: Show the terminated instances
      debug:
        msg: "Terminated instances: {{ terminated_instances.instances | map(attribute='instance_id') | list }}"
